apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: {{ .Values.name }}
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
