---
applications:
  # - name: grafana-subchart
  #   valueFiles:
  #     - /enviroments/cluster1/values/grafana/grafana.yaml
  #   path: apps/grafana

  # - name: whoami
  #   valueFiles: 
  #     - /enviroments/cluster1/values/whoami/whoami.yaml
  #   path: apps/whoami

  - name: grafana
    valueFiles:
      - $values/enviroments/cluster1/values/grafana/grafana.yaml
    repository: https://grafana.github.io/helm-charts 
    targetRevision: 6.36.3
    chart: grafana