tags:
  cluster1: true
  cluster2: false

traefik-cluster1:
  deployment:
    kind: DaemonSet
  service:
    type: ClusterIP
  ports:
    web:
      port: 80
    websecure:
      port: 443
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
  ingressClass:
    enabled: true
  ingressRoute:
    dashboard:
      enabled: false
  logs:
    access:
      enabled: true
  hostNetwork: true
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
  globalArguments: []
  nodeSelector:
    node-role.kubernetes.io/ingress: ""
  tolerations:
    - key: "node-role.kubernetes.io/ingress"
      operator: "Exists"
  securityContext:
    capabilities:
      drop: [ALL]
      add: [NET_BIND_SERVICE]
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0