---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-cluster2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Andrik001/argocd.git
    targetRevision: main
    path: helmCharts/traefik
    helm:
      valueFiles:
        - values-cluster-2.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true