tags:
  cluster1: false
  cluster2: false

cluster1:
  apps:
    grafana:
      name: grafana-cluster1
      valueFiles:
        - values-cluster1.yaml
      destination:
        name: cluster-1
        namespace: grafana
        project: admin-cluster1

    traefik:
      name: traefik-cluster1
      valueFiles:
        - values-cluster1.yaml
      destination:
        name: cluster-1
        namespace: traefik
        project: admin-cluster1

cluster2:
  apps:
    grafana:
      name: grafana-cluster2
      valueFiles:
        - values-cluster2.yaml
      destination:
        name: cluster-2
        namespace: grafana
        project: dev-cluster2

    traefik:
      name: traefik-cluster2
      valueFiles:
        - values-cluster2.yaml
      destination:
        name: cluster-2
        namespace: traefik
        project: dev-cluster1