tags:
  cluster1: false
  cluster2: false

cluster1:
  apps:
    grafana:
      name: grafana-cluster1
      valueFiles:
        - values-cluster-1.yaml
      destination:
        name: cluster-1
        namespace: grafana
    traefik:
      name: traefik-cluster1
      valueFiles:
        - values-cluster-1.yaml
      destination:
        name: cluster-1
        namespace: traefik

cluster2:
  apps:
    grafana:
      name: grafana-cluster2
      valueFiles:
        - values-cluster-1.yaml
      destination:
        name: cluster-2
        namespace: grafana
    traefik:
      name: traefik-cluster2
      valueFiles:
        - values-cluster-1.yaml
      destination:
        name: cluster-2
        namespace: traefik