apiVersion: v1
kind: Service
metadata:
  name: test
  labels: app.kubernetes.io/instance: grafana-cl2
spec:
  type: ClusterIP
  ports:
    - port: 4444
      targetPort: http
      protocol: TCP
      name: http
  selector: app.kubernetes.io/instance: grafana-cl2