apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.name }}
spec:
  ports:
  - port: {{ .Values.app.service.port }}
    protocol: TCP
    targetPort: {{ .Values.app.service.targetPort }}
  selector:
    app: {{ .Values.app.name }}
  sessionAffinity: None
  type: {{ .Values.app.service.type }}