---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cluster1
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: git@github.com:Andrik001/argocd.git 
    targetRevision: main
    path: helmCharts/grafana
    helm: 
      valueFiles:
        - values-cluster1.yaml
  destination:
    name: cluster-1
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true