---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.applications.name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Andrik001/argocd.git
    targetRevision: main
    path: charts/{{ .Values.applications.name }}
    helm:
      valueFiles:
{{- range .Values.applications.valueFiles }}
{{ "-" | indent 8 }} {{ . }}
{{- end }}
  destination:
    name: cluster-1
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
