{{ define "argocd.app" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Andrik001/argocd.git
    targetRevision: main
    path: helmCharts/{{ .namespace }}
    helm:
      valueFiles:
      {{- range .valueFiles }}
        - {{ . }}  
      {{ end -}}
  destination:
    name: {{ .destination.name }}
    namespace: {{ .destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
---
{{ end }}