---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-cluster-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Andrik001/argocd.git
    targetRevision: main
    path: helmCharts/argocd
    helm:
      parameters:
        - name: "cluster2.tag"
          value: "cluster2"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false