---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: main-cluster1
  namespace: argocd
spec:
  project: admin-main
  source:
    repoURL: git@github.com:Andrik001/argocd.git
    targetRevision: main
    path: helmCharts/argocd
    helm:
      parameters:
        - name: "tags.cluster1"
          value: "true"
  destination:
    name: cluster-1
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false